[project]
name = "e-library-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "olukayode-asemudara", email = "theolukayodeasemudara@gmail.com" },
    { name = "Clement Nwafor", email = "" },
    { name = "Ajulo Gbemi", email = "" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pymysql>=1.2.0",
    "sqlalchemy>=2.0.52",
    "pydantic>=2.13.4",
    "mysql-connector-python>=26.7.0",
    "uvicorn>=0.52.4",
    "data>=0.4",
]

[project.scripts]
e-library-system = "e_library_system:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
